#!/usr/bin/env bash
#
# SPDX-FileCopyrightText: 2023 Wiktor Kwapisiewicz <wiktor@metacode.biz>
# SPDX-License-Identifier: CC0-1.0

set -euxo pipefail

# Move faster checks near the top of this script.  For example
# codespell is very fast. cargo fmt does not need to download crates etc.

codespell
# We're using nightly to properly group imports, see rustfmt.toml
cargo +nightly fmt -- --check
cargo clippy --all -- -D warnings
cargo deny check -D warnings -A duplicate -A accepted
cargo test --all
